[package]
name = "citadel-frontend"
version = "0.0.10"
edition = "2021"
license = "MIT"
readme = "README.md"
description = "The frontend of the citadel compiler backend"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
