[package]
name = "citadel-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
citadel-frontend = { path = "../frontend" }

[dev-dependencies]
citadel-irparser = { path = "../irparser" }
