[package]
name = "citadel"
version = "0.1.0"
edition = "2021"

[dependencies]
citadel-irparser = { path = "../irparser" }
citadel-backend = { path = "../backend" }
clap = { version = "4.5.4", features = ["derive"] }
